name: GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'
      - 'upload.html'
      - 'upload_confirmation.html'
      - '_config.yml'
      - '_includes/**'
      - '_layouts/**'
      - '_posts/**'
      - 'assets/**'
      - 'css/**'
      - 'js/**'
      - '.github/workflows/pages.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Update to the latest version

    # Add a delay to prevent multiple builds from being triggered simultaneously
    - name: Delay
      run: sleep 5

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1  # Update to the latest version
      with:
        ruby-version: '3.0'  # Specify a valid Ruby version

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}  # Ensure the secret name matches
        publish_dir: ./_site
        # Ensure the correct branch is specified for deployment
        publish_branch: gh-pages

    - name: Debug GitHub Actions Environment
      run: |
        echo "GITHUB_REPOSITORY: ${{ github.repository }}"
        echo "GITHUB_REF: ${{ github.ref }}"
        echo "GITHUB_SHA: ${{ github.sha }}"
        echo "GITHUB_ACTOR: ${{ github.actor }}"
        echo "GITHUB_WORKFLOW: ${{ github.workflow }}"
        echo "GITHUB_ACTION: ${{ github.action }}"
        echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
        echo "GITHUB_EVENT_PATH: ${{ github.event_path }}"
        echo "GITHUB_WORKSPACE: ${{ github.workspace }}"
        echo "GITHUB_ACTION_PATH: ${{ github.action_path }}"
        echo "GITHUB_RUN_ID: ${{ github.run_id }}"
        echo "GITHUB_RUN_NUMBER: ${{ github.run_number }}"
        echo "GITHUB_RETENTION_DAYS: ${{ github.retention_days }}"
        echo "GITHUB_TRIGGERING_ACTOR: ${{ github.triggering_actor }}"
        echo "GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}"
        echo "GITHUB_ENV: ${{ github.env }}"
        echo "GITHUB_PATH: ${{ github.path }}"
        echo "GITHUB_JOB: ${{ github.job }}"
        echo "GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}"
        echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
        echo "GITHUB_REF_PROTECTED: ${{ github.ref_protected }}"
        echo "GITHUB_REF_TYPE: ${{ github.ref_type }}"
        echo "GITHUB_BASE_REF: ${{ github.base_ref }}"
        echo "GITHUB_HEAD_REF: ${{ github.head_ref }}"
        echo "GITHUB_SERVER_URL: ${{ github.server_url }}"
        echo "GITHUB_API_URL: ${{ github.api_url }}"
        echo "GITHUB_GRAPHQL_URL: ${{ github.graphql_url }}"
      shell: bash